---
- name: Configure DNS via IdM
  gather_facts: false
  hosts: localhost
  vars_files:
    vault.yaml
  roles:
    - role: ipa
      tags:
        - ipa

- name: Configure Load Balancer Host
  become: true
  gather_facts: false
  hosts: helper
  roles:
    - role: firewalld
      tags:
        - firewalld
    - role: haproxy
      tags:
        - haproxy
    - role: httpd
      tags:
        - httpd

- name: Initialize VMware and Deploy Cluster Nodes
  gather_facts: false
  hosts: localhost
  vars_files:
    vault.yaml
  roles:
    - role: vmware_init
  tasks:
    - name: Deploy Bootstrap/Control Plane Nodes
      vars:
        - _node_scope:
            - bootstrap
            - control-plane
      block:
        - name: Create Bootstrap/Control Plane VMs
          ansible.builtin.import_role:
            name: vmware

        - name: Start Bootstrap/Control Plane VMs
          ansible.builtin.import_role:
            name: boot_instances

    - name: Deploy Compute Nodes
      vars:
        - _node_scope:
            - compute
      block:
        - name: Create Compute VMs
          ansible.builtin.import_role:
            name: vmware

        - name: Start Compute VMs
          ansible.builtin.import_role:
            name: boot_instances

- name: Destroy Bootstrap Node and Remove from HAProxy
  become: true
  gather_facts: false
  hosts: helper
  vars_files:
    vault.yaml
  roles:
    - name: bootstrap_cleanup
      tags:
        - bootstrap-cleanup

- name: Post Cluster Configuration
  gather_facts: false
  hosts: localhost
  vars_files:
    vault.yaml
  tasks:
    - name: Wait 10 Minutes for API
      ansible.builtin.uri:
        method: GET
        url: "https://api.{{ base_domain }}:6443/readyz"
        validate_certs: false
      delay: 10
      register: api_results
      retries: 60
      until:
        - api_results.status == 200

    - name: Deploy Sealed Secrets Controller
      ansible.builtin.include_role:
        name: sealed_secrets
      tags:
        - sealed-secrets

    - name: Stop CSR Auto Approver
      ansible.builtin.include_role:
        name: csr_auto_approve_cleanup
      tags:
        - csr-auto-approve-cleanup

    - name: Wait for Cluster Operators
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: ClusterVersion
        kubeconfig: "{{ installation_directory }}/auth/kubeconfig"
        name: version
      delay: 15
      register: cluster_version_results
      retries: 120
      tags:
        - wait_for_cluster_operators
      until:
        - (cluster_version_results.resources[0] | community.general.json_query(_query_available) | first | bool) is true
        - (cluster_version_results.resources[0] | community.general.json_query(_query_progressing) | first | bool) is false
      vars:
        _query_available: "status.conditions[?type=='Available'].status"
        _query_progressing: "status.conditions[?type=='Progressing'].status"
