---
- name: Setup DNS and Create RHCOS VMs on VMware
  hosts: localhost
  vars_files:
    - vault.yaml
  roles:
    - role: ipa
      tags:
        - ipa
    - role: vmware
      tags:
        - vmware

- name: Setup Load Balancer Host
  become: yes
  gather_facts: no
  hosts: helper
  roles:
    - role: dhcpd
      when:
        - not use_static_ip
      tags:
        - dhcpd
    - role: firewalld
      tags:
        - firewalld
    - role: haproxy
      tags:
        - haproxy
    - role: httpd
      tags:
        - httpd

- name: Boot Red Hat CoreOS Nodes
  gather_facts: no
  hosts: localhost
  vars_files:
    - vault.yaml
  roles:
   - role: boot-instances
     tags:
        - boot-instances

- name: Destroy Bootstrap
  become: yes
  gather_facts: no
  hosts: helper
  vars_files:
  - vault.yaml
  roles:
    - name: bootstrap-cleanup
      tags:
        - bootstrap-cleanup

- name: Post Cluster Configuration
  gather_facts: no
  hosts: localhost
  vars_files:
    - vault.yaml
  tasks:
    - name: Deploy Sealed Secrets Controller
      ansible.builtin.include_role:
        name: sealed-secrets
      tags:
        - sealed-secrets

    - name: Stop CSR Auto Approver
      ansible.builtin.include_role:
        name: csr-auto-approve-cleanup
      tags:
        - csr-auto-approve-cleanup
