---
- name: Build Vars for {{ item }}
  ansible.builtin.include_tasks:
    file: loop-common.yaml

- name: Create VMs (Cluster Placement) for {{ item }}
  community.vmware.vmware_guest:
    advanced_settings: "{{ vapp_properties }}"
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ hostvars[item].datastore }}"
    disk: "{{ hostvars[item].disk | default([]) | list }}"
    folder: "/{{ vcenter_datacenter }}/vm/{{ cluster_name }}"
    guest_id: rhel8_64Guest
    hardware:
      cpu_reservation: "{{ hostvars[item].cpu_reservation | default(0) }}"
      memory_mb: "{{ hostvars[item].memory }}"
      mem_reservation: "{{ hostvars[item].mem_reservation | default(0) }}"
      nested_virt: "{{ hostvars[item].nested_virt | default(False) }}"
      num_cpu_cores_per_socket: "{{ hostvars[item].cores }}"
      num_cpus: "{{ hostvars[item].cores }}"
      version: "{{ vcenter_hardware_version | int }}"
    hostname: "{{ vcenter_hostname }}"
    name: "{{ item }}.{{ base_domain }}"
    password: "{{ vcenter_password }}"
    state: present
    template: "{{ ova_vm_name }}"
    username: "{{ vcenter_username }}"
    validate_certs: no
  register: vmware_guest_results
