- name: Start VMs in Node Scope
  community.vmware.vmware_guest:
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    hostname: "{{ vcenter_hostname }}"
    name: "{{ item }}.{{ base_domain }}"
    password: "{{ vcenter_password }}"
    state: poweredon
    username: "{{ vcenter_username }}"
    validate_certs: "{{ validate_certs }}"
  loop: "{{ groups[provision_group] }}"
  when:
    - hostvars[item].node_type in _node_scope

- name: Wait 30 Minutes for SSH
  ansible.builtin.wait_for:
    connect_timeout: 20
    host: "{{ hostvars[item].ip }}"
    port: 22
    sleep: 10
    timeout: 1800
  loop: "{{ groups[provision_group] }}"
  when:
    - hostvars[item].node_type in _node_scope
