- name: Install Packages
  yum:
    name:
      - httpd
      - php
      - python3-policycoreutils
    state: latest
  tags:
    - install-packages

- name: Allow httpd to listen on TCP port {{ httpd_port }}
  seport:
    ports: "{{ httpd_port }}"
    proto: tcp
    setype: http_port_t
    state: present

- name: Copy httpd.conf Template
  template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
    setype: httpd_config_t

- name: Copy Ignition PHP Script
  copy:
    src: files/ignition-downloader.php
    dest: /var/www/html/ignition-downloader.php
    owner: root
    group: root
    mode: 0644
    setype: httpd_sys_content_t

- name: Copy ignition files
  copy:
    src: "{{ installation_directory }}/{{ item }}"
    dest: /var/www/html/
    owner: root
    group: root
    mode: 0644
    setype: httpd_sys_content_t
  loop:
    - bootstrap.ign
    - master.ign
    - worker.ign

- name: Restore SELinux Contexts in Document Root
  shell: restorecon -R /var/www/html

- name: Enable httpd port in firewall
  firewalld:
    port: "{{ httpd_port }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  tags:
    - firewalld

- name: Enable/Start httpd Service
  systemd:
    name: httpd
    state: started
    enabled: yes