- name: Install firewalld Package
  ansible.builtin.yum:
    name:
      - firewalld
    state: present
  tags:
    - install-packages

- name: Enable/Start firewalld Service
  ansible.builtin.systemd:
    enabled: true
    name: firewalld
    state: started
