apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: "Cluster Role for CSR Auto Approver"
  name: csr-auto-approver
rules:
- apiGroups:
    - v1
  resources:
    - Nodes
  verbs:
    - get
    - list
- apiGroups:
    - certificatesigningrequests.certificates.k8s.io
    - signers.certificates.k8s.io
  resources:
    - '*'
  verbs:
    - '*'
