- name: Delete VMs
  community.vmware.vmware_guest:
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    force: yes
    hostname: "{{ vcenter_hostname }}"
    name: "{{ item }}.{{ base_domain }}"
    password: "{{ vcenter_password }}"
    state: absent
    username: "{{ vcenter_username }}"
    validate_certs: no
  register: vmware_guest_results
  with_items:
    - "{{ groups[provision_group] }}" 
